[build]
builder = "nixpacks"
buildCommand = "cd server && pnpm install"

[deploy]
startCommand = "cd server && pnpm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3001" 