[build]
builder = "nixpacks"
buildCommand = "cd server && pnpm install"

[deploy]
startCommand = "cd server && pnpm start"
healthcheckPath = "/api/tasks"
healthcheckTimeout = 100

[env]
NODE_ENV = "production"
PORT = "3001" 