services:
  - type: web
    name: daily-todo-api
    env: node
    buildCommand: cd server && pnpm install
    startCommand: cd server && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001 