name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Install root dependencies
        run: pnpm install

      - name: Install client dependencies
        run: cd client && pnpm install

      - name: Install server dependencies
        run: cd server && pnpm install

      - name: Build client
        run: cd client && pnpm build
        env:
          VITE_API_URL: https://daily-todo-api.onrender.com

      - name: Copy client build to server
        run: |
          rm -rf server/public
          mkdir -p server/public
          cp -r client/dist/* server/public/

      - name: Deploy to render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json"